dist: trusty
sudo: required
language: node_js
node_js:
  - '6.10'

addons:
sonarqube:
    organization: "kasperlauge-github"
    token:
      secure: "p82ytx7fep/qODJgkxQYw8op+aVTUFhkMziPOt5GA8lxb+3LPhrt/v0QbQ6Pz/LqPOcFyrWKOrlVvQb5tUNsoSORN6hWia5GG/6PR/UDcsBEzohF/PZT1QIt9i0jqsMopRDYnkOj1s9pBvZ/uzXI86tfI/lYRhjD+1ALvmuo33qPI2Qw93Fy4L2t0AlE0sDVNdqfQPAt02gHBRlg2m3hxlGApIHghscK94EqIf0hWey4R3Yv2+tbbZIatUxwc59KRJaGB1SECsK5RoIBgoTzJ2xXgu6jgEXzDQRijrvyr6Nvuo9VuoSAneZUVn0Qby5VSZVn4EpZ6Z1DNVCPY1zS7oFOwr3YY+yURAVMSgXqMo9V1jjqLNSJ7uTfW3PyOZdpzjlxwrw+filWk1Ned5fS+J7Vof0qj1818RPmXnCoUuaO99hUEpGwnp1PvDDWIdhzEjyciUWuOJz7AWl7OiyusXElU1h7nuESyWIs5exaNcQekpR0hkqcSGDB8fzIJ7Ya3LXWLtY+EBsxzVDIvfqD/99rHsZS3EWKcINTW/nseuJXEaQIViJhJ+AKZozsll+BFe2KKg8kHqzaot8EiRiFnTyruJfpWxRXh4ACLYwlpN855UeyQcnzSEVS5YzOfHR7KDAfaMEiYGrvadN4CMdBYQ5zyyNUO1D9QtLFMdSsBqE="
jdk:
  - oraclejdk8
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install

script:
  - sonar-scanner
  - ng test --single-run

cache:
  directories:
    - '$HOME/.sonar/cache'
